# Generated by Django 4.0.6 on 2022-07-21 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageStateTransitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Packages', to='main.package')),
            ],
        ),
    ]
