# Generated by Django 4.0.6 on 2022-07-21 21:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_packagestatetransitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagestatetransitions',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 21, 26, 31, 183955, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
