# Generated by Django 4.0.6 on 2022-07-21 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_packagestatetransitions_time_alter_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
