# Generated by Django 4.0.6 on 2022-07-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(default='Karma', max_length=60),
            preserve_default=False,
        ),
    ]
