# Generated by Django 4.0.6 on 2022-07-21 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='customer_id',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Customers'}, on_delete=django.db.models.deletion.CASCADE, related_name='Customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='driver_id',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Drivers'}, on_delete=django.db.models.deletion.CASCADE, related_name='Drivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
