# Generated by Django 4.0.6 on 2022-07-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_package_customer_id_alter_package_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagestatetransitions',
            name='state',
            field=models.CharField(choices=[('RE', 'Registered'), ('PR', 'In Preparation'), ('OW', 'On way'), ('DE', 'Delivered'), ('SU', 'Suspended')], default='RE', max_length=2),
        ),
    ]
