# Generated by Django 4.0.6 on 2022-08-02 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_rename_type_route_route_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='current_warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Current_Car_W', to='main.warehouse'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driver_id',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'groups__name': 'Drivers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Drivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='route_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.route'),
        ),
        migrations.AlterField(
            model_name='driverdata',
            name='current_warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.warehouse'),
        ),
        migrations.AlterField(
            model_name='driverdata',
            name='route_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.route'),
        ),
        migrations.AlterField(
            model_name='package',
            name='car_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cars', to='main.car'),
        ),
        migrations.AlterField(
            model_name='package',
            name='current_warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Current_W', to='main.warehouse'),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Destination_W', to='main.warehouse'),
        ),
        migrations.AlterField(
            model_name='package',
            name='origin_warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Origin_W', to='main.warehouse'),
        ),
        migrations.AlterField(
            model_name='package',
            name='route_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Routes', to='main.route'),
        ),
    ]
