# Generated by Django 4.0.6 on 2022-07-29 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('registration_number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('filled', models.IntegerField()),
                ('current_warehouse', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Current_Car_W', to=settings.AUTH_USER_MODEL)),
                ('driver_id', models.ForeignKey(blank=True, default=None, limit_choices_to={'groups__name': 'Drivers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Drivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('state', models.CharField(choices=[('RE', 'Registered'), ('ER', 'En Route'), ('DE', 'Delivered'), ('AW', 'At warehouse')], default='RE', max_length=2)),
                ('origin_latitude', models.FloatField()),
                ('origin_longitude', models.FloatField()),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('car_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cars', to='main.car')),
                ('current_warehouse', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Current_W', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Destination_W', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_latitude', models.FloatField()),
                ('origin_longitude', models.FloatField()),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('interwarehouse', models.BooleanField()),
                ('state', models.CharField(max_length=64)),
                ('length', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('location_latitude', models.FloatField()),
                ('location_longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PackageStateTransitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('RE', 'Registered'), ('ER', 'En Route'), ('DE', 'Delivered'), ('AW', 'At warehouse')], default='RE', max_length=2)),
                ('time', models.DateTimeField()),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Packages', to='main.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='origin_warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Origin_W', to='main.warehouse'),
        ),
        migrations.AddField(
            model_name='package',
            name='reciever_id',
            field=models.ForeignKey(default=None, limit_choices_to={'groups__name': 'Customers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recievers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='route_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Routes', to='main.route'),
        ),
        migrations.AddField(
            model_name='package',
            name='sender_id',
            field=models.ForeignKey(default=None, limit_choices_to={'groups__name': 'Customers'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Senders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='route_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.route'),
        ),
    ]
