# Generated by Django 4.0.6 on 2022-07-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='current_warehouse',
        ),
        migrations.AddField(
            model_name='car',
            name='origin_warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Current_Car_W', to='main.warehouse'),
        ),
    ]
