# Generated by Django 4.0.6 on 2022-07-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_car_current_warehouse_car_origin_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='state',
            field=models.CharField(choices=[('Registered', 'Registered'), ('En Route', 'En Route'), ('Delivered', 'Delivered'), ('At warehouse', 'At warehouse')], default='Registered', max_length=60),
        ),
        migrations.AlterField(
            model_name='packagestatetransitions',
            name='state',
            field=models.CharField(choices=[('Registered', 'Registered'), ('En Route', 'En Route'), ('Delivered', 'Delivered'), ('At warehouse', 'At warehouse')], default='Registered', max_length=60),
        ),
    ]
