# Generated by Django 4.0.6 on 2022-07-30 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_package_reciever_id_remove_package_sender_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='current_warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Current_W', to='main.warehouse'),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Destination_W', to='main.warehouse'),
        ),
    ]
