# Generated by Django 4.0.6 on 2022-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_length_route_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='origin_warehouse',
            new_name='current_warehouse',
        ),
        migrations.AddField(
            model_name='car',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
