# Generated by Django 4.0.6 on 2022-08-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_driverdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='type',
            new_name='route_type',
        ),
    ]
