# Generated by Django 4.0.6 on 2022-08-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_car_current_warehouse_alter_car_driver_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='route_order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
